# Generated by Django 4.2.9 on 2024-02-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_photo",
                    models.ImageField(blank=True, null=True, upload_to="Vehicle_Image"),
                ),
                ("vehicle_number", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=100)),
                ("product_quantity", models.CharField(max_length=100)),
                ("delivery_challan_number", models.CharField(max_length=100)),
                ("purchase_order_number", models.CharField(max_length=100)),
                ("purchase_date", models.CharField(max_length=100)),
                (
                    "quality_check_status",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail")], max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "usertype",
                    models.CharField(
                        choices=[
                            ("Normal User", "nomal_user"),
                            ("Quality Check User", "quality_check"),
                        ],
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(fields=("id",), name="id"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="VehicleApp.vendor",
            ),
        ),
    ]
