# Generated by Django 4.2.9 on 2024-02-24 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("VehicleApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="product_quantity",
        ),
    ]
